name: Remote Dispatch Action Initiator

on:
  push:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
          curl -X post https://api.github.com/repos/CatgirlsRodeo/dev.catgirls.rodeo/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.access_token }} \
          -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'


